# workflow that deploys to "pastebin-write" lambda service from "write" directory

name: deploy_write


on:
  # triggers when there are new changes in write branch
  push:
    branches: [ "prod-write" ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # type of runner that the job will run on
    runs-on: ubuntu-latest

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      # setup AWS
      - name: setting up aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # zip write directory
      - name: zip write directories
        run: |
          cd backend/write && zip -r write.zip ./*
          aws lambda update-function-code --function-name=pastebin-write --zip-file=fileb://write.zip
          rm write.zip